MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.fpn_ResNet101_conv5_body
  FASTER_RCNN: True
  MASK_TRAIN_ON: True
  MASK_ON: True
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: '/home/wudi/PycharmProjects/ApolloScape_InstanceSeg/data/pretrained_model/resnet101_caffe.pth'
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER:  200000
  STEPS: [0, 20000, 40000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  NON_LOCAL: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs
  RESOLUTION: 28  # (output mask resolution) default 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14  # default 7
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
TRAIN:
  #SCALES: (800,)
  SCALES: (1600, 2000)  # If it's 0, means that we don't resize it
  MAX_SIZE: 2000
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 4000  # Per FPN level, 2000 default
  CE_FINETUNE_WIGHT: ( 1,  1.20,    6.4,         14.35,      1.   , 2.48,   1.53427976,    4.088)
  SNAPSHOT_ITERS: 400

TEST:
  SCORE_THRESH: 0.1
  SCALE: 0  # 2710
  MAX_SIZE: 3384  # 3384
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  RPN_POST_NMS_TOP_N: 2000  # 1000 default
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.9
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION
    COORD_HEUR: UNION
    H_FLIP: True
    SCALES: (1200, 1700, 2200) # we don't need 3384 because the first SCALE include it!
    MAX_SIZE: 3384
    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    ASPECT_RATIOS: ()
    ASPECT_RATIO_H_FLIP: False
  MASK_AUG:
    ENABLED: True
    HEUR: SOFT_AVG
    H_FLIP: True
    SCALES: (1200, 1700, 2200) # we don't need 3384 because the first SCALE include it!
    MAX_SIZE: 3384
    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    ASPECT_RATIOS: ()
    ASPECT_RATIO_H_FLIP: False

